### ISSUE TITLE
Error in importing yampy

### ISSUE THREAD

**Issue by Draffodx** [yammer/yam-python#22]
When trying to import yampy in a python script I get an internal import error from Yampy.

Here is the error:

Traceback (most recent call last):
     File "C:\Users\raffertd\Desktop\Gamification\yammer_parser.py", line 1, in <mo
    dule>
        import yampy
      File "C:\Python34\lib\site-packages\yampy\__init__.py", line 22, in <module>
        from authenticator import Authenticator
     ImportError: No module named 'authenticator'

This occurs when simply trying to import yampy

    import yampy

**Comment by tonybaloney** [comment]
this is because you are using Python 3, I'm getting the same issue.

try `pip install --upgrade -e 'git+https://github.com/yammer/yam-python@master#egg=yampy'`

The maintainers of this project need to publish a new version

**Comment by jonburge1** [comment]
Ah. Me too: http://stackoverflow.com/q/38101382/6519905

**Comment by tonybaloney** [comment]
I actually published another package, 'yampy3' because this project looks stale as just a direct clone. 
Try that out. Then I will probably change it to use from future import relative, which is the best way to handle both versions IMO (or just use absolute throughout) 

Get Outlook for iOS




On Thu, Jun 30, 2016 at 3:21 AM +1000, "jonburge1" <notifications@github.com> wrote:












Ah. Me too: http://stackoverflow.com/q/38101382/6519905

**Comment by jonburge1** [comment]
Awesome! Thanks. Updated SO question
